# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tilePicker_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_imageTilePicker(object):
    def setupUi(self, imageTilePicker):
        imageTilePicker.setObjectName("imageTilePicker")
        imageTilePicker.resize(766, 540)
        self.centralwidget = QtWidgets.QWidget(imageTilePicker)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.canvasView = QtWidgets.QVBoxLayout()
        self.canvasView.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.canvasView.setObjectName("canvasView")
        self.gridLayout.addLayout(self.canvasView, 0, 0, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.classNameCombo = QtWidgets.QComboBox(self.centralwidget)
        self.classNameCombo.setObjectName("classNameCombo")
        self.classNameCombo.addItem("")
        self.classNameCombo.addItem("")
        self.classNameCombo.addItem("")
        self.classNameCombo.addItem("")
        self.classNameCombo.addItem("")
        self.classNameCombo.addItem("")
        self.classNameCombo.addItem("")
        self.classNameCombo.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.classNameCombo)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tileSelectRadio = QtWidgets.QRadioButton(self.centralwidget)
        self.tileSelectRadio.setCheckable(False)
        self.tileSelectRadio.setObjectName("tileSelectRadio")
        self.horizontalLayout.addWidget(self.tileSelectRadio)
        self.spectrumSelectRadio = QtWidgets.QRadioButton(self.centralwidget)
        self.spectrumSelectRadio.setCheckable(False)
        self.spectrumSelectRadio.setObjectName("spectrumSelectRadio")
        self.horizontalLayout.addWidget(self.spectrumSelectRadio)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.tileSizeEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.tileSizeEdit.setReadOnly(True)
        self.tileSizeEdit.setObjectName("tileSizeEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.tileSizeEdit)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.bandSelectCombo = QtWidgets.QComboBox(self.centralwidget)
        self.bandSelectCombo.setObjectName("bandSelectCombo")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.bandSelectCombo)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.pushButton)
        self.gridLayout.addLayout(self.formLayout, 1, 1, 1, 1)
        self.loadedImagesTableLayout = QtWidgets.QVBoxLayout()
        self.loadedImagesTableLayout.setObjectName("loadedImagesTableLayout")
        self.gridLayout.addLayout(self.loadedImagesTableLayout, 0, 1, 1, 1)
        self.selectedTilesTableLayout = QtWidgets.QFormLayout()
        self.selectedTilesTableLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.selectedTilesTableLayout.setObjectName("selectedTilesTableLayout")
        self.gridLayout.addLayout(self.selectedTilesTableLayout, 1, 0, 1, 1)
        imageTilePicker.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(imageTilePicker)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 766, 21))
        self.menubar.setObjectName("menubar")
        self.menuObjects = QtWidgets.QMenu(self.menubar)
        self.menuObjects.setObjectName("menuObjects")
        self.menuImage = QtWidgets.QMenu(self.menubar)
        self.menuImage.setObjectName("menuImage")
        self.menuClassification = QtWidgets.QMenu(self.menubar)
        self.menuClassification.setObjectName("menuClassification")
        self.menuUnsupervised = QtWidgets.QMenu(self.menuClassification)
        self.menuUnsupervised.setObjectName("menuUnsupervised")
        self.menuSupervised = QtWidgets.QMenu(self.menuClassification)
        self.menuSupervised.setObjectName("menuSupervised")
        self.menuAdaBoost = QtWidgets.QMenu(self.menuSupervised)
        self.menuAdaBoost.setObjectName("menuAdaBoost")
        self.menuRandom_Forest = QtWidgets.QMenu(self.menuSupervised)
        self.menuRandom_Forest.setObjectName("menuRandom_Forest")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        imageTilePicker.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(imageTilePicker)
        self.statusbar.setObjectName("statusbar")
        imageTilePicker.setStatusBar(self.statusbar)
        self.actionAdd_New_Object_Type = QtWidgets.QAction(imageTilePicker)
        self.actionAdd_New_Object_Type.setObjectName("actionAdd_New_Object_Type")
        self.actionLoad_Object_Config = QtWidgets.QAction(imageTilePicker)
        self.actionLoad_Object_Config.setObjectName("actionLoad_Object_Config")
        self.actionLoad_Images = QtWidgets.QAction(imageTilePicker)
        self.actionLoad_Images.setObjectName("actionLoad_Images")
        self.actionExport_Objects_to_File = QtWidgets.QAction(imageTilePicker)
        self.actionExport_Objects_to_File.setObjectName("actionExport_Objects_to_File")
        self.actionK_Means = QtWidgets.QAction(imageTilePicker)
        self.actionK_Means.setObjectName("actionK_Means")
        self.actionAdaBoostTrain = QtWidgets.QAction(imageTilePicker)
        self.actionAdaBoostTrain.setObjectName("actionAdaBoostTrain")
        self.actionAdaBoostClassify = QtWidgets.QAction(imageTilePicker)
        self.actionAdaBoostClassify.setObjectName("actionAdaBoostClassify")
        self.actionRfTrain = QtWidgets.QAction(imageTilePicker)
        self.actionRfTrain.setObjectName("actionRfTrain")
        self.actionRfClassify = QtWidgets.QAction(imageTilePicker)
        self.actionRfClassify.setObjectName("actionRfClassify")
        self.menuObjects.addAction(self.actionAdd_New_Object_Type)
        self.menuObjects.addAction(self.actionLoad_Object_Config)
        self.menuObjects.addAction(self.actionExport_Objects_to_File)
        self.menuImage.addAction(self.actionLoad_Images)
        self.menuUnsupervised.addAction(self.actionK_Means)
        self.menuAdaBoost.addAction(self.actionAdaBoostTrain)
        self.menuAdaBoost.addAction(self.actionAdaBoostClassify)
        self.menuRandom_Forest.addAction(self.actionRfTrain)
        self.menuRandom_Forest.addAction(self.actionRfClassify)
        self.menuSupervised.addAction(self.menuAdaBoost.menuAction())
        self.menuSupervised.addAction(self.menuRandom_Forest.menuAction())
        self.menuClassification.addAction(self.menuUnsupervised.menuAction())
        self.menuClassification.addAction(self.menuSupervised.menuAction())
        self.menubar.addAction(self.menuImage.menuAction())
        self.menubar.addAction(self.menuObjects.menuAction())
        self.menubar.addAction(self.menuClassification.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(imageTilePicker)
        QtCore.QMetaObject.connectSlotsByName(imageTilePicker)

    def retranslateUi(self, imageTilePicker):
        _translate = QtCore.QCoreApplication.translate
        imageTilePicker.setWindowTitle(_translate("imageTilePicker", "Tile Picker"))
        self.label.setText(_translate("imageTilePicker", "Object Type"))
        self.classNameCombo.setItemText(0, _translate("imageTilePicker", "Tree"))
        self.classNameCombo.setItemText(1, _translate("imageTilePicker", "Snow"))
        self.classNameCombo.setItemText(2, _translate("imageTilePicker", "Water"))
        self.classNameCombo.setItemText(3, _translate("imageTilePicker", "Asphalt"))
        self.classNameCombo.setItemText(4, _translate("imageTilePicker", "Concrete"))
        self.classNameCombo.setItemText(5, _translate("imageTilePicker", "Soil"))
        self.classNameCombo.setItemText(6, _translate("imageTilePicker", "Grass"))
        self.classNameCombo.setItemText(7, _translate("imageTilePicker", "Paint"))
        self.tileSelectRadio.setText(_translate("imageTilePicker", "Tile Select Mode"))
        self.spectrumSelectRadio.setText(_translate("imageTilePicker", "Spectrum Select Mode"))
        self.label_3.setText(_translate("imageTilePicker", "Tile Size"))
        self.tileSizeEdit.setText(_translate("imageTilePicker", "10"))
        self.label_4.setText(_translate("imageTilePicker", "Band"))
        self.pushButton.setText(_translate("imageTilePicker", "PushButton"))
        self.menuObjects.setTitle(_translate("imageTilePicker", "Objects"))
        self.menuImage.setTitle(_translate("imageTilePicker", "Image"))
        self.menuClassification.setTitle(_translate("imageTilePicker", "Classification"))
        self.menuUnsupervised.setTitle(_translate("imageTilePicker", "Unsupervised"))
        self.menuSupervised.setTitle(_translate("imageTilePicker", "Supervised"))
        self.menuAdaBoost.setTitle(_translate("imageTilePicker", "AdaBoost"))
        self.menuRandom_Forest.setTitle(_translate("imageTilePicker", "Random Forest"))
        self.menuHelp.setTitle(_translate("imageTilePicker", "Help"))
        self.actionAdd_New_Object_Type.setText(_translate("imageTilePicker", "Add New Object Type"))
        self.actionLoad_Object_Config.setText(_translate("imageTilePicker", "Load Object Config"))
        self.actionLoad_Images.setText(_translate("imageTilePicker", "Add Image"))
        self.actionExport_Objects_to_File.setText(_translate("imageTilePicker", "Export Objects to File"))
        self.actionK_Means.setText(_translate("imageTilePicker", "K-Means"))
        self.actionAdaBoostTrain.setText(_translate("imageTilePicker", "Train"))
        self.actionAdaBoostClassify.setText(_translate("imageTilePicker", "Classify"))
        self.actionRfTrain.setText(_translate("imageTilePicker", "Train"))
        self.actionRfClassify.setText(_translate("imageTilePicker", "Classify"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    imageTilePicker = QtWidgets.QMainWindow()
    ui = Ui_imageTilePicker()
    ui.setupUi(imageTilePicker)
    imageTilePicker.show()
    sys.exit(app.exec_())

